Fix order in DestroyWindow to avoid trying to remove already-zeroed handle from keepAlivePool.
Fixes the following exception:
mscorlib.System.ArgumentException: An item with the same key has already been added. Key: 140336378563728
    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException
    at System.Collections.Generic.Dictionary`2[[System.IntPtr, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryInsert
    at System.Collections.Generic.Dictionary`2[[System.IntPtr, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Add
    at System.Windows.Forms.XplatUICocoa.CreateWindow
    at System.Windows.Forms.XplatUI.CreateWindow
    at System.Windows.Forms.NativeWindow.CreateHandle
    at System.Windows.Forms.Control.CreateHandle